# Generated by CoffeeScript 1.9.1
(->
  removeClassFromElements = undefined
  removeDOMElement = undefined
  removeElementsByClass = undefined
  removeClassFromElements = (classname) ->
    i = undefined
    x = undefined
    x = document.getElementsByClassName(classname)
    i = undefined
    i = 0
    while i < x.length
      x[i].classList.remove classname
      i++
    return

  removeElementsByClass = (className) ->
    elements = undefined
    elements = document.getElementsByClassName(className)
    elements[0].parentNode.removeChild elements[0]  while elements.length > 0
    return

  removeDOMElement = (id) ->
    document.getElementById(id).remove()  if document.getElementById(id)
    return

  animate = (object, property, start_value, end_value, time) ->
    frame_rate = 0.06
    # 60 FPS
    frame = 0
    delta = (end_value - start_value) / time / frame_rate
    console.log delta
    console.log start_value
    handle = setInterval((->
      frame++
      value = start_value + delta * frame
      # console.log(value);
      object.style[property] = value + 'px'
      if value == end_value
        clearInterval handle
      return
    ), 1 / frame_rate)
    return

  String::startsWith = (text) ->
    @substr(0, text.length) is text

  String::contains = (text) ->
    @indexOf(text) isnt -1

  chrome.extension.onMessage.addListener (request, sender) ->
    checked = undefined
    invalid = undefined
    pageLinks = undefined
    passed = undefined
    queued = undefined
    rpBox = undefined
    totalvalid = undefined
    pageLinks = document.getElementsByTagName("a")
    totalvalid = pageLinks.length
    queued = 0
    checked = 0
    invalid = 0
    passed = 0
    rpBox = undefined
    removeDOMElement "ALP_ReportBox"
    ((pg) ->
      a = undefined
      blacklist = undefined
      blacklisted = undefined
      cacheType = undefined
      checkType = undefined
      e = undefined
      h = undefined
      i = undefined
      j = undefined
      matas = undefined
      meta_txt = undefined
      r = undefined
      rbClose = undefined
      rbHeader = undefined
      rbSettings = undefined
      rcss = undefined
      reportBox = undefined
      reportStyle = undefined
      rid = undefined
      tblcss = undefined
      tdlcss = undefined
      tdrcss = undefined
      titles = undefined
      blacklist = request.bl
      blacklisted = undefined
      cacheType = request.ca
      checkType = request.ct
      reportStyle = document.createElement("style")
      reportStyle.setAttribute "rel", "stylesheet"
      reportStyle.setAttribute "type", "text/css"
      document.getElementsByTagName("head")[0].appendChild reportStyle
      reportStyle.appendChild document.createTextNode("#ALP_ReportBox{font-weight: bold; width: 250px; position: fixed; right:0px; top: 0px; background: #fff; margin: 20px; padding: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 14px; border-radius: 5px; z-index: 99999; box-shadow: 0px 0px 3px rgba(0,0,0,1);}")
      reportBox = document.createElement("div")
      rbHeader = document.createElement("div")
      rbClose = document.createElement("div")
      rbClose.innerHTML = "&times;"
      rbClose.setAttribute "id", "ALP_RB_Close"
      rbSettings = document.createElement("div")
      reportBox.setAttribute "id", "ALP_ReportBox"
      rbHeader.innerHTML = "Link Results"
      document.getElementsByTagName("body")[0].appendChild reportBox
      rpBox = document.getElementById("ALP_ReportBox")
      a = undefined
      e = undefined
      h = undefined
      i = undefined
      j = undefined
      r = undefined
      rcss = undefined
      rid = undefined
      tblcss = undefined
      tdlcss = undefined
      tdrcss = undefined
      rid = "ALT_VIEWER_PLUS"
      e = (t) ->
        document.getElementsByTagName t

      a = (o, a) ->
        att = undefined
        att = o.getAttribute(a)
        return "alt未設定"  if a is "alt" and att is null
        att

      return  if document.getElementById(rid)
      i = e("img")
      return  if i.length <= 0
      r = document.createElement("div")
      rcss = "padding:0px;position:fixed;top:0;right:0;border:solid #ccc 1px;z-index:999;max-height:100%;overflow: auto;"
      tblcss = " style='border-collapse:collapse;background:hsla(0,0%,0%,.75);'"
      tdlcss = " style='padding:0 .5em 0 0;border-bottom:solid #fff 2px;text-align:right;'"
      tdrcss = " style='padding:0 0 0 1em;border-bottom:solid #fff 2px;text-align:left;background-color:hsla(0,0%,0%,.45);color:#F0EA30;width:250px;'"
      r.id = rid
      r.style.cssText = rcss
      h = "<style>\n@-webkit-keyframes anime1 {\n0% {opacity: .2;}\n100% {opacity: 1;}\n}\n.img_blink{-webkit-animation: anime1 0.5s ease 0s infinite alternate;}\n</style>"
      h += "<table" + tblcss + " class=\"ATT_VIEWER_TABLE\">"
      j = 0
      h += "<tr><td colspan=\"2\" style=\"padding:1em 0 0 1em;border-bottom:solid #fff 2px;text-align:left;color:#fff;white-space:pre-wrap;max-width:500px;line-height:1;font-size: 12px;\">"
      h += "<span class=\"ALT_VIEWER_CLOSE\" style=\"background-color: hsla(0,100%,100%,1);color: #000;position: absolute;right: 0;top: 0;padding: 0.5em 1em;\">Close✕</span>"
      matas = ""
      Array::forEach.apply document.querySelectorAll("title, meta, h1"), [(e, i, a) ->
        i = undefined
        attrs = undefined
        inn = undefined
        out = undefined
        out = e.outerHTML.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/'/g, "&#39;").replace(/</g, "&lt;").replace(/>/g, "&gt;") + "\n"
        inn = e.innerHTML
        out.replace inn, "<span style=\"color:#F0EA30;\">" + inn + "</span>"
        attrs = e.attributes
        i = attrs.length - 1
        while i >= 0
          out = out.replace(new RegExp(attrs[i].name, "g"), "<span style=\"color:#70BE47;\">" + attrs[i].name + "</span>").replace(new RegExp(attrs[i].value, "g"), "<span style=\"color:#F55A21;\">" + attrs[i].value + "</span>")
          i--
        matas += out + "\n"
        return
      ]
      meta_txt = matas
      h += meta_txt
      h += "</td></tr>"
      while j < i.length
        h += (if j % 252 is 0 then "<tr>" else "<tr>")
        h += "<td" + tdlcss + "><img style='max-width: 350px;vertical-align:bottom;' src=" + a(i[j], "src") + "></td><td" + tdrcss + ">" + a(i[j], "alt") + "</td></tr>"
        j++
      titles = ""
      Array::forEach.apply document.querySelectorAll("[title]"), [(e, i, a) ->
        i = undefined
        attrs = undefined
        newout = undefined
        out = undefined
        title = undefined
        out = e.outerHTML.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/'/g, "&#39;").replace(/</g, "&lt;").replace(/>/g, "&gt;") + "\n"
        attrs = e.attributes
        i = attrs.length - 1
        while i >= 0
          if attrs[i].name is "title"
            title = attrs[i].value
            newout = out.replace("title", "<span style=\"color:#70BE47;\">title</span>").replace(title, "<span style=\"color:#F55A21;\">" + title + "</span>")
            h += "<tr><td" + tdlcss + " style='max-width: 350px;vertical-align:top;'><span style='max-width: 350px;display: inline-block;line-height:1;font-size: 12px;color: #fff;text-align: left;padding:.5em 0 0 .5em;overflow: hidden;'>" + newout + "</span></td>"
            h += "<td class=\"ALT_VIEWER_TITLE\" style=\"padding:1em 0 1em 1em;border-bottom:solid #fff 2px;text-align:left;background-color:hsla(0,0%,0%,.45);color:#F55A21;width:250px;overflow: hidden;vertical-align: top;\">" + title + "</td></tr>"
          i--
        titles += out + "\n"
        return
      ]
      h += "</table>"
      e("body")[0].appendChild r
      r.innerHTML = h
      r.onclick = ->

      document.querySelector(".ALT_VIEWER_CLOSE").onclick = ->
        elm = document.querySelector("#ALT_VIEWER_PLUS")
        elm.remove()  if elm
        return

      window.scrollTo 0, 0
      Array::forEach.apply document.querySelectorAll(".ATT_VIEWER_TABLE img"), [(e, i, a) ->
        e.addEventListener "mouseover", ((event) ->
          filename_ex = undefined
          filename_ex = event.target.src.match(".+/(.+?)([?#;].*)?$")[1]
          elm = document.querySelector("[src$=\"" + filename_ex + "\"]")
          if elm
            elm.style.border = "solid 3px #F82F66"
            elm.classList.add "img_blink"
            # アニメーション
            top = elm.getBoundingClientRect().top + window.scrollY
            window.scrollTo(0, top)
          return
        ), false
        return
      ]
      Array::forEach.apply document.querySelectorAll(".ATT_VIEWER_TABLE img"), [(e, i, a) ->
        e.addEventListener "mouseout", ((event) ->
          filename_ex = undefined
          filename_ex = event.target.src.match(".+/(.+?)([?#;].*)?$")[1]
          elm = document.querySelector("[src$=\"" + filename_ex + "\"]")
          if elm
            elm.style.border = "none"
            elm.classList.remove "img_blink"
          return
        ), false
        return
      ]
      Array::forEach.apply document.querySelectorAll(".ATT_VIEWER_TABLE .ALT_VIEWER_TITLE"), [(e, i, a) ->
        e.addEventListener "mouseover", ((event) ->
          title = undefined
          title = event.target.innerText
          elm = document.querySelector("[title$=\"" + title + "\"]")
          if elm
            document.querySelector("[title$=\"" + title + "\"]").style.border = "solid 3px #F82F66"
            document.querySelector("[title$=\"" + title + "\"]").classList.add "img_blink"
          return
        ), false
        return
      ]
      Array::forEach.apply document.querySelectorAll(".ATT_VIEWER_TABLE .ALT_VIEWER_TITLE"), [(e, i, a) ->
        e.addEventListener "mouseout", ((event) ->
          title = undefined
          title = event.target.innerText
          elm = document.querySelector("[title$=\"" + title + "\"]")
          if elm
            elm.style.border = "none"
            elm.classList.remove "img_blink"
          return
        ), false
        return
      ]
      document.getElementById("ALP_RB_Close").onclick = ->
        removeDOMElement "ALP_ReportBox"
        return

      chrome.extension.onMessage.removeListener doStuff
      return
    ) pageLinks
    true

  return
).call this
